DATA_DIR: '../../data/raw/shopee-product-matching/'

BERT:
  MODEL_NAME: 'bert'
  CHECKPOINTS_DIR: '../../reports/checkpoints/language/'
  BINARIES_DIR: '../../reports/binaries/language/'
  DATA_DIR: '../../data/raw/shopee-product-matching/'

  MAX_TOKEN_LENGTH: 512
  MAX_LENGTH: 64

  BASELINE_CONFIG:
    NUM_ENCODER_LAYERS: 12
    MODEL_DIMENSION: 768
    NUM_HEADS: 8
    DROPOUT: 0.1
    EMBEDDING_DIM: 768
    HIDDEN_SIZE: 768
    INTERMEDIATE_SIZE: 3072
    NUM_EMBEDDINGS: 30522

  TOKENIZER_CHECKPOINT: 'bert-base-uncased'


ViT:
  NAME: 'vision-transformer'
  CHECKPOINTS_DIR: '../../reports/checkpoints/vision/'
  BINARIES_DIR: '../../reports/binaries/vision/'
  DATA_DIR: '../../data/raw/shopee-product-matching/'

  TRANSFORMS:
    HEIGHT: 224
    WIDTH: 224

  BASELINE_CONFIG:
    ENCODER_LAYERS: 6
    NUM_HEADS: 8
    EMBEDDING_DIM: 768
    IMAGE_HEIGHT: 224
    IMAGE_WIDTH: 224
    NUM_CHANNELS: 3
    NUM_HEADS: 8
    DROPOUT: 0.1
    PATCH_SIZE: 16
    MAX_TOKEN_SIZE: 512
    HIDDEN_DIM: 3072


HYPERPARAMETERS:
  LEARNING_RATE: 3e-4
  TRAIN_BS: 32
  VALID_BS: 64
  OPTIMIZER: 'adam'
  SCHEDULER: 'CosineAnnealingLR'
  T_0: 25
  T_MAX: 30000
  WEIGHT_DECAY: 1e-6
  WARMUP_STEPS: 0
  MIN_LR: 1e-6
  LM: 'BERT'
  CNN: 'ViT'

SEED: 1337
