DATA_DIR: '../../data/raw/shopee-product-matching/'

LANGUAGE:
  MODEL_NAME: 'bert'
  CHECKPOINTS_DIR: '../../reports/checkpoints/language/'
  BINARIES_DIR: '../../reports/binaries/language/'
  DATA_DIR: '../../data/raw/shopee-product-matching/'

  MAX_LENGTH: 512

  BASELINE_CONFIG:
    ENCODER_LAYERS: 6
    MODEL_DIMENSION: 512
    NUM_HEADS: 8
    DROPOUT: 0.1
    EMBEDDING_DIM: 512
    HIDDEN_SIZE: 256

  TOKENIZER_CHECKPOINT: 'bert-base-uncased'


VISION:
  NAME: 'vision-transformer'
  CHECKPOINTS_DIR: '../../reports/checkpoints/vision/'
  BINARIES_DIR: '../../reports/binaries/vision/'
  DATA_DIR: '../../data/raw/shopee-product-matching/'

  TRANSFORMS:
    HEIGHT: 512
    WIDTH: 512

  BASELINE_CONFIG:
    ENCODER_LAYERS: 6
    MODEL_DIMENSION: 512
    NUM_HEADS: 8
    DROPOUT: 0.1


HYPERPARAMETERS:
  LEARNING_RATE: 3e-4
  TRAIN_BS: 32
  VALID_BS: 64
  OPTIMIZER: 'adam'
  SCHEDULER: 'CosineAnnealing'
  T_0: 25
  WEIGHT_DECAY: 1e-6
  WARMUP_STEPS: 0
  MIN_LR: 1e-6

SEED: 1337
